### ISSUE TITLE
Unable to insert external images 

### ISSUE THREAD

**Issue by filippogambarota** [brentthorne/posterdown#101]
Hi, I'm trying to import some external images in `.svg` and `.png` format.  Both using the `![caption](path)` and `knitr::include_graphics(path)` syntax no image appear in the specific location. Only the symbol in the figure appears. 
<img width="131" alt="Screenshot_2" src="https://user-images.githubusercontent.com/29129681/66380739-4ad15d80-e9b8-11e9-95d0-dd9ac410ee7d.png"

**Comment by brentthorne** [comment]
Hi @filippogambarota !

To give you a better answer can you please answer a few questions for me, what part of the document are you adding the images to (the body of the .rmd file or is it in the YAML heading)? Is the image locally stored or is it grabbed from a hyperlink? Can you reproduce the same problem on a new working template of the poster style you chose as well as with the image you wish to insert?

Thanks,

Brent
