### ISSUE TITLE
how to render a pdf 

### ISSUE THREAD

**Issue by rherinjakad** [brentthorne/posterdown#104]
I am a beginner so excuse me if the answer is obvious : 

How to render a pdf as output instead of html ? 

Thank you !

**Comment by brentthorne** [comment]
Hello @rherinjakad thank you for using posterdown! I will point you to the wiki instructions for this package which has a section on [how to render](https://github.com/brentthorne/posterdown/wiki/Installation-&-Usage-Guide#rendering-posters) your poster :tada: 

Cheers!

**Comment by rherinjakad** [comment]
Thank you very much,

Daniel RAKOTOMALALA
Doctorant en économie (CEMOI)  - Université de La Réunion



Le ven. 25 oct. 2019 à 18:43, Brent Thorne <notifications@github.com> a
écrit :
