### ISSUE TITLE
Adjust title font size

### ISSUE THREAD

**Issue by hollzzar** [brentthorne/posterdown#107]
Is there a way to adjust the font size of the title in posterdown_betterland? I saw that there's a way to do that for the middle text using middle_fontsize. I tried title_fontsize but that didn't work. Thanks!

**Comment by brentthorne** [comment]
Hello @hollzzar !

The good news is that this is possible using the YAML option `title_textsize` as described in this [wiki table](https://github.com/brentthorne/posterdown/wiki/posterdown_html#title-box). Not sure if you are using an older fork of posterdown but all sizing of text is now uniformly referred to as `text` rather then `font`. Also the `middle` section is now referred to as `main`.

Hope this helps!

**Comment by hollzzar** [comment]
Thanks @brentthorne! I think you're right that I was looking at an older fork.
