### ISSUE TITLE
option to specify text color of author names

### ISSUE THREAD

**Issue by dr-JT** [brentthorne/posterdown#110]
I know these templates are meant to be easy and accessible for anyone to use and so there is a certain amount of balance you want to achieve with customizability and ease of use.

I am using the betterland template option right now...

The primary color for my poster is a yellow (slightly darker yellow). However, I prefer text to not have the color yellow as it makes it harder to read. With the current settings I cannot change the text color of author names without changing the background color of the main section. 

Overall this is not a big deal but just thought I'd add it.

Also thanks for making this template! Great job!

**Comment by brentthorne** [comment]
Luckily the YAML option `author_textcol` should work! I guess I missed adding it to the wiki but it is in the code!

**Comment by dr-JT** [comment]
Wonderful! :)
