### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by noah-padgett** [brentthorne/posterdown#27]
Hi Brent -- Hope you're doing well! I am very excited to give posterdown a try. But, I've run into an issue installing the package. I am on Window's 10 trying to install based on your instructions and this is the message I receive in return:

> devtools::install_github("brentthorne/posterdown")

Error: HTTP error 401.
  Bad credentials

  Rate limit remaining: 58/60
  Rate limit reset at: 2019-01-24 22:19:23 UTC

Any ideas on how to resolve the issue? I tried restarted R and my computer, but for some reason, this message pops up.

Thank you in advance for any help!

**Comment by brentthorne** [comment]
Hello!

This seems like its something other than posterdown to me, do you have `devtools` installed?

```r
install.packages("devtools")
```

If that's done already then maybe it's something else, I will take a deeper look into it soon when I have a chance. 

Also check out this [issue](https://github.com/r-lib/devtools/issues/1566) from the devtools repo and see if it's similar!

Hope it works and you can start enjoying posterdown soon!

Cheers

**Comment by noah-padgett** [comment]
The issue is resolved! Thank you sending me to the right place. It is very much appreciated and I was able to get the template compiled! :)

**Comment by brentthorne** [comment]
That's good to here, as a heads up some nice new features are coming soon (mayeb even today) which will give you even more styling options :+1:  :smile:
