### ISSUE TITLE
First issue - two typos in README

### ISSUE THREAD

**Issue by higgi13425** [brentthorne/posterdown#4]
Small fixes - change "sudent", "right", "feild" -
change
"As a graduate sudent, I found that it is almost a right of passage to take early research and analysis and generate a conference poster allowing for critical feedback as well as meeting the people in your feild." 
to
"As a graduate student, I found that it is almost a rite of passage to take early research and analysis and generate a conference poster allowing for critical feedback as well as meeting the people in your field."

**Comment by brentthorne** [comment]
Ah yes, typos are my kryptonite!

Thank you @higgi13425

**Comment by higgi13425** [comment]
I am still figuring out the fork/clone/branch/PR thing.Hoping I can help.I'm probably more of a vignette writer than a skilled coder, but I hope I can recruit a few skilled people to this important project.
Peter
    On Monday, January 7, 2019, 4:30:25 PM EST, Brent Thorne <notifications@github.com> wrote:  
 
 
Ah yes, typos are my kryptonite!

Thank you @higgi13425

**Comment by brentthorne** [comment]
Sounds great! I look forward to any and all contributions to make this a better package for all! If there are other missing key features you think I should add to my TODO list at the end of the ReadMe please let me know.

**Comment by higgi13425** [comment]
Hi Brent, I tried to knit to poster down_pdf with the default template (no edits),and I get this error
(see screenshot below)Am I missing some key dependencies?Cairo? libfreetype?libcairo?
RStudio version  Version 1.1.463R version R version 3.5.1
All packages are up to date.
Peter 
    On Monday, January 7, 2019, 7:12:29 PM EST, Brent Thorne <notifications@github.com> wrote:  
 
 
Sounds great! I look forward to any and all contributions to make this a better package for all! If there are other missing key features you think I should add to my TODO list at the end of the ReadMe please let me know.

**Comment by brentthorne** [comment]
Hello Peter, 

Unfortunately the image is not showing up here on the issue's thread. Perhaps you could me email the screen capture directly at **bthorne2@brocku.ca** and I can have a look at it. It's likely that I will create a new issue thread once I see what the problem is.

Thanks again

**Comment by higgi13425** [comment]
Is there a way to fix this incompatibility?
Found biblatex control file version 3.5, expected version 3.4.
This means that your biber (2.11) and biblatex (3.12) versions are incompatible.
See compat matrix in biblatex or biber PDF documentation.
    On Tuesday, January 8, 2019, 6:35:33 PM EST, Peter Higgins <higgi13425@yahoo.com> wrote:  
 
  I now have two 'posterdown' templates.Tried the other one, got a different error - seems more related to Biber
List of 6
 $ out.width : chr "80%"
 $ fig.width : num 4.5
 $ fig.align : chr "center"
 $ echo      : logi TRUE
 $ fig.height: num 5
 $ fig.cap   : chr "Another figure showing how base R plots might look on this poster!"

  |.................................................................| 100%
  ordinary text without R code


/usr/local/bin/pandoc +RTS -K512m -RTS test.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output test.tex --template /Users/peterhiggins/Library/R/3.5/library/posterdown/rmarkdown/templates/posterdown_pdf/resources/template.tex --highlight-style tango --pdf-engine pdflatex --biblatex 
output file: test.knit.md

INFO - This is Biber 2.11
INFO - Logfile is 'test.blg'
INFO - Reading 'test.bcf'
ERROR - Error: Found biblatex control file version 3.5, expected version 3.4.
This means that your biber (2.11) and biblatex (3.12) versions are incompatible.
See compat matrix in biblatex or biber PDF documentation.
INFO - ERRORS: 1
Error: Failed to build the bibliography via biber
Execution halted
    On Tuesday, January 8, 2019, 6:29:53 PM EST, Brent Thorne <notifications@github.com> wrote:  
 
 
Closed #5.
