### ISSUE TITLE
Assorted font questions

### ISSUE THREAD

**Issue by higgi13425** [brentthorne/posterdown#45]
1. what controls which font appears between backticks in text,
i.e. Welcome to `posterdown` !

what controls the font for    `posterdown`     ??

2. I can control the font of title by inserting
\fontfamily{qhv}\selectfont
at the beginning of the quoted text of the title, just after the quotation, and before the actual text.
This is great.

3. However, this does not seem to work for authors or institutions.
Puzzling - is there a way to do this? 
I just want these to be in the same font as the title.
Or does this have to do with the hacky way needed to make multiple authors work?
(If so, can you borrow code from the rticles package?)

What is currently controlling the font family for authors or institutions?

4. I can control the font of body text by inserting
\fontfamily{qag}\selectfont before the first chunk of body text - and it carries forward to all of the other body text (excepting that surrounded by backticks).
This is great.

5. However, if I change the first sectitle font by inserting
\fontfamily{bch}\selectfont 
before the text starts, this only affects the first sectitle, and does not carry forward.
Any way to make this carry forward?

BTW, I am finding the font codes at the link below.
https://www.overleaf.com/learn/latex/Font_typefaces  

6. I am puzzled by what the font_family parameter in the YAML header does control.
Does it control some font somewhere?
What am I missing?

7. Also, any way to adjust the spacing between words?
When I use
\fontfamily{qhv}\selectfont in the title, the words are a bit too close together.
Other fonts are usually OK, but not always.

I can do it in a hacky way with 
\space 
where needed.
But it seems like there is probably something more elegant.

thanks,
Peter

**Comment by brentthorne** [comment]
The font issues are where latex has been challenging for me, as I am still trying to wrap my head around how most of it works. With that said, fonts are important and this will be up in the list for priority. 

I will also note that there really shouldn't b more than two fonts within the document (excluding the ones for code chunks). 

I will play around with different fixes and update the package when I have a better grasp of how to manipulate font type dynamically throughout the document. 

Thanks again @higgi13425 for you patients!

**Comment by brentthorne** [comment]
The focus of posterdown has shifted to html/CSS and I will no longer be supporting latex output so I will close this issue and all others related to latex specific templates.

If anyone is interested in taking on the latex side of this package I'd be glad to pass on the work I have done/ the responsibility of maintaining it!

**Comment by Benjipapa** [comment]
how do i reduce fontsize of headers without adding hash e.g Introduction, Aims etc
