### ISSUE TITLE
Vertical spacing between level 1 and level 2 bullets

### ISSUE THREAD

**Issue by higgi13425** [brentthorne/posterdown#48]
Code in Rmd

* Patient 3 had:
  - High CRP
  - Colonic dilation
  - Failed IV steroids

results in a large vertical space between

Patient 3 had:

and 

  - High CRP

and a large vertical space after

  - Failed IV steroids

is there any way to control/eliminate this?

**Comment by brentthorne** [comment]
This could be dependant on where the list is placed within the document after it has been knit. I would need to see or have a minimal working example of the problem in order to test out fixes for this. If you can provide one that would be great, thank you!

**Comment by higgi13425** [comment]
Here is an example (.Rmd below).In this case (in Windows)- no indents for 2nd level bullet- surprisingly large vertical space before bulleted list begins.On mac, - surprising space between level 1 and level 2 bullets
---# PLEASE SEE THE README for in depth description github.com/brentthorne/posterdown##---POSTER SIZE & DEFAULT FONT---#poster_height: "38in" # height in inches of posterposter_width: "45in" # width in inches of posterfont_family: "palatino" # choose from typical latex fonts (example: "palatino")font_size: "30pt" #please see github.com/brentthorne/posterdown for compatible options.
#---TITLE BOX OPTIONS---##ESSENTIALStitle: '\fontfamily{phv}\selectfont Using posterdown to generate reproducible conference posters via RMarkdown > Knitr > Markdown > Pandoc > Latex > PDF workflow'author: "Author One^1^ Author Two^2^"affiliation: "^1^Department of Poster Layouts, University of Markdown; ^2^Deparment of Another Institution, Institution University"#STYLE & FORMATTINGtitlebox_bgcol: "008080"  #Colour of the Title Box backgroundtitlebox_bordercol: "0b4545" #Colour of the title Box border.titlebox_shape: "all"titlebox_borderwidth: "1cm"title_textcol: "ffffff" #colour of title textauthor_textcol: "0b4545" # Colour of author textaffiliation_textcol: "FFFFFF" # Colour of affiliation texttitle_textsize: "Huge"         # Poster title fontsizeauthor_textsize: "Large"       # Author list font sizeaffiliation_textsize: "large"  # Affiliation font size#ADDING LOGOSlogoleft_name: 'Figures/posterdownlogo'logoleft_width: '3in'logoleft_xshift: '1in'logoleft_yshift: '1in'logoright_name: 'Figures/posterdownlogo'logoright_width: '3in'logoright_xshift: '-1in'logoright_yshift: '1in'
#---POSTER BODY OPTIONS---#body_bgcol: "ffffff" #colour of the poster main backgroundbody_textsize: "normalsize"    # Size of the main poster body textbody_textcol: "000000" # Colour of main text in the body of postercolumn_numbers: 4 # Number of columns that the poster hascolumn_margins: "0.5in" # Margin spacing for columnscolumnline_col: "008080" #colour columnline_width: "0pt" #width of line between each column#SECTION TITLE STYLINGsectitle_textcol: "ffffff" # Colour of the poster section titlessectitle_bgcol: "0b4545" # Colour of the section title boxsectitle_bordercol: "0b4545" # Colour of the border around the section title box.sectitle_borderwidth: "2mm" # Thicknes of the section title box bordersectitle_boxshape: "uphill" # Changes the shape of the section title box.
#---BIBLIOGRAPHY OPTIONS---#bibliography: MyLibrary # name of the .bib file used for referencingbibliography_spacing: 0.8 # sets the multiplier for line spacing of bibliography spacing (between 0 and 1)bibliography_textsize: "small"  # size of the bibliography text size (handy for one too many references!)
#---OTHER---#cite_col: "CC0000" #colour of ciation elementsurl_col: "008080" #colour of url linkslink_col: "008080" #colour of other links within the posterfootnote_textcol: "ffffff" # Colour of footnote text if usedoutput: posterdown::posterdown_pdf---
```{r, include=FALSE}knitr::opts_chunk$set(echo = FALSE, results = 'asis',fig.height = 3.5, fig.width = 4.5, out.width = "100%", warning = FALSE, fig.align = 'center', message = FALSE, dev='cairo_pdf')```

# Introduction
Welcome to `posterdown` ! This is my attempt to provide a semi-smooth workflow for those who wish to take their `RMarkdown` skills to the conference world. Many creature comforts from `RMarkdown` are available in this package such as `Markdown` section notation, figure captioning, and even citations like this one [@holden_identifying_2012] The rest of this example poster will show how you can insert typical conference poster features into your own document. 
# Study Site
Here is a map made to show the study site using `ggplot2`, `ggspatial`, and `sf` and you can even reference this with a hyperlink, this will take you to **Figure \ref{mymapfig}**. Lorem ipsum dolor sit amet, [@middleton_geological_nodate] consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \vspace{1cm}
```{r, out.width="80%", fig.cap='This is a map of Canada, the ggspatial package is great for GIS folks in R! \\label{mymapfig}', cache=TRUE}library(ggplot2)library(ggspatial)library(tidyverse)library(ggthemes)library(sf)
canada <- read_sf("data/Canada.geojson")
yukon <- canada %>%   filter(PROV == "YT")
ggplot() +  ggspatial::layer_spatial(canada,fill = "grey80", colour = "grey60") +  ggspatial::layer_spatial(yukon,fill = "yellow", colour = "black") +  ggspatial::annotation_north_arrow(location = "br",pad_y = unit(1,"cm"),pad_x = unit(0.7,"cm"), which_north = "true", style = north_arrow_orienteering()) +  ggspatial::annotation_scale(location = "br",style = "ticks") +  coord_sf() +  theme_pander() +  theme(legend.position = "none") +  NULL```
# Objectives
1. Easy to use reproducible poster design. 2. Integration with `RMarkdown`.3. Easy transition from `posterdown` to `thesisdown` or `rticles`
\lipsum[2]\lipsum[4]
# Methods
This package uses the same workflow approach as the `RMarkdown` you know and love. Basically it goes from RMarkdown > Knitr > Markdown > Pandoc > Latex > PDF.
# Results
Usually you want to have a nice table displaying some important results that you have calcualated. In posterdown this is as easy as using the `kable` table formatting you are probably use to as per typical `RMarkdown` formatting. I suggesting checking out the `kableExtra` package and its in depth documentation on customizing these tables found [here](https://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf).
\vspace{1cm}
```{r}library(kableExtra)library(ggplot2)
data("iris")
kable(iris[1:4,],align = "c", caption = "Tables are a breeze with Kable and Kable extra package!", booktabs = TRUE) %>%   kable_styling(latex_options = c("striped","HOLD_position"),full_width = TRUE, font_size = 25)
```* Here we will put in some bullet points  + We like to use bullets  + They are brief* And force us to be concise  + Users of text and space
```{r, out.width='100%', fig.height=4.5, fig.cap='Using ggplot and patchwork to generate a layout of multiple plots in one figure. The iris dataset was used to generate (a) a line graph, (b) a scatterplot, and (c) a boxplot all together!'}
library(tidyverse)library(patchwork)library(ggthemes)
theme_set(theme_gray() + theme_tufte() + theme(legend.position = "none"))
base <- ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, colour = Species))  p_point <- base + geom_point()p_line  <- base + geom_line() p_area  <- base + geom_area()p_box1  <- ggplot(iris) + geom_boxplot(aes(x = Species, y = Sepal.Length, fill = Species))p_box2  <- ggplot(iris) + geom_boxplot(aes(x = Species, y = Sepal.Width, fill = Species))
p_line +   {p_point + p_box1} +  plot_layout(ncol = 1) + plot_annotation(tag_levels = "a", tag_prefix = "(",tag_suffix = ")")
```

```{r, out.width='85%', fig.width=4.5, fig.height=4, fig.cap='Another typical plot using ggplot, this time with a different theme and r code chunk options for fig.width and fig.height.'}
library(ggplot2)library(ggthemes)
ggplot(data = iris, aes(x = Sepal.Length, y = Sepal.Width, colour = Species)) +  geom_point() +  theme_tufte() +  labs(x = "Sepal Length", y = "Sepeal Width") +  NULL
```

```{r, out.width='80%', fig.width=4.5, fig.align='center', echo=TRUE, fig.height=5, fig.cap='Another figure showing how base R plots might look on this poster!'}
# Here is some code for people# to look at and be in awe of!!!!library(ggplot2)library(ggthemes)
ggplot(data=iris,       aes(x = Sepal.Width,           y = Sepal.Length,           colour = Species)) +  geom_point() +  theme_tufte() +  NULL
```

# Next Steps
There is still **A LOT** of work to do on this package which include (but are note limited to): 
- Better softcoding for front end user options in YAML- Images in the title section for logo placement which is a common attribut to posters as far as I have come to know.- Figure out compatiability with `natbib` which wasn't working during the initial set up.- MUCH BETTER PACKAGE DOCUMENTATION. For example, there is nothing in the README...- Include References section only if initiated by the user like in RMarkdown.
\small\printbibliography

    On Sunday, February 3, 2019, 6:34:59 PM EST, Brent Thorne <notifications@github.com> wrote:  
 
 
This could be dependant on where the list is placed within the document after it has been knit. I would need to see or have a minimal working example of the problem in order to test out fixes for this. If you can provide one that would be great, thank you!

**Comment by brentthorne** [comment]
The focus of posterdown has shifted to html/CSS and I will no longer be supporting latex output so I will close this issue and all others related to latex specific templates.

If anyone is interested in taking on the latex side of this package I'd be glad to pass on the work I have done/ the responsibility of maintaining it!
