### ISSUE TITLE
Question about rendering during poster development

### ISSUE THREAD

**Issue by higgi13425** [brentthorne/posterdown#49]
Is there a way to 
1. speed up rendering by cache=TRUE for code chunks?
or
2. have constantly updating rendering with infinite moon reader (from the xaringan package) 
with xaringan::inf_mr('poster_example.Rmd')

**Comment by brentthorne** [comment]
1. `cache = TRUE` will definately speed up the render after the first knit. 

2. I haven't actually tried the infinate moonreader functionality yet from xaringan but it sounds pretty interesting. It may not work well with LaTeX kniting, however that may be solved in the next while as I am currently developing an html version of `posterdown_pdf`. It may work once that is created.

**Comment by higgi13425** [comment]
Thanks!
    On Sunday, February 3, 2019, 6:33:11 PM EST, Brent Thorne <notifications@github.com> wrote:  
 
    
   -    
cache = TRUE will definately speed up the render after the first knit.

   -    
I haven't actually tried the infinate moonreader functionality yet from xaringan but it sounds pretty interesting. It may not work well with LaTeX kniting, however that may be solved in the next while as I am currently developing an html version of posterdown_pdf. It may work once that is created.

**Comment by brentthorne** [comment]
This is now possible with `posterdown_html`

**Comment by higgi13425** [comment]
Cool!!
