### ISSUE TITLE
How to adjust font size in the middle?

### ISSUE THREAD

**Issue by mrsensible** [brentthorne/posterdown#56]
Since I am preparing an A1 size poster, I want to reduce the font size in the middle. I tested `middle_textsize = 70pt` but it doesn't seem to work. 
```
middle_fontfamily: "Roboto"
middle_textcol: "#FFFFFF90"
middle_textsize: "70pt"
main_findings:
  - "Make **better posters** with <br> RMarkdown + **posterdown**."
```
Is there a solution?

**Comment by brentthorne** [comment]
There sure is, see the `middle_fontsize:` option now in the YAML options. 

Also thanks for finding this, it was  miss on my end! Just reinstall posterdown and add the YAML option into your existing `.Rmd` and you should be good to go changing the font size!

**Comment by Benjipapa** [comment]
how do i reduce fontsize of headers without adding hash e.g Introduction, Aims etc
