### ISSUE TITLE
Keep default template simple?

### ISSUE THREAD

**Issue by lwjohnst86** [brentthorne/posterdown#57]
Great package, thanks!

A couple of suggestions/comments:

- Could there be an option to not create a folder when creating a new poster template? I like to have my files in a particular location and don't need a whole new folder just for the poster.
- Could there be a function to *only* create the template poster R Markdown file? Right now it creates a `.bib` file, a `Figure` folder, and adds a logo in the `Figure` folder. It would be nicer (at least for me) if I could just have the Rmd file and nothing more. (Of course, a link to the documentation, which you've already wonderfully filled out, would likely be necessary for this simpler function.

I might take a stab at completing a PR on this since having a poster Rmd generator is really useful.

**Comment by brentthorne** [comment]
I agree! The reason why I have it set up this way right now is for those who are using R/RMarkdown for the first time. I tried to have it as a sort of "_here's how you can layout your project/ notice how you can reference images or other files within folders_" model to make it somewhat intuitive.

My intentions are indeed to make a lightweight version of the template, I honestly may even make a "pure markdown" version of the template as to not scare away non-R user's. 

Feel free to send a PR if you come up with/ have time to come up with one as it would be greatly appreciated!

**Comment by brentthorne** [comment]
This has been implemented well enough for my liking so I will close this issue! Thanks again @lwjohnst86
