### ISSUE TITLE
Reduce package install size/ add LaTeX poster as a secondary download 

### ISSUE THREAD

**Issue by brentthorne** [brentthorne/posterdown#58]
In an attempt to manage the size of this package I think it would be good to remove the LaTeX components of the initial installation of the package. Possibly use something like:

```r
posterdown::install_posterdown_latex()
```

For those who still wish to use it down the road.

Just not sure how to tackle it yet, so any suggestions are welcome!

**Comment by lwjohnst86** [comment]
You might not need to remove the latex poster templates. Its not them that cause the problem but the json data files, as mentioned in #65.

**Comment by brentthorne** [comment]
Thanks for this I will close this issue now that the travis build is working from your merge. I will likely add to the skeleton.Rmd but only use base R and loripsum text just so that the whole poster is filled (ish) for those who want to see what it would look like before inputting their own information (ie those who are new to rmarkdown in general). I've added you as a contributor in the description file as well.

Thanks again

**Comment by lwjohnst86** [comment]
Thanks a lot!
