### ISSUE TITLE
Error in finding 

### ISSUE THREAD

**Issue by vratchaudhary** [brentthorne/posterdown#60]
Thanks for the amazing package. It will be very helpful. However, I am running into this issue while trying to knit. I am attaching log file for any inside.
All I changed for tempelate is the text, so it did knit for me prior to customization but not after change of text. Thanks for help.
[ccm_poster_pig_Data.log](https://github.com/brentthorne/posterdown/files/3095430/ccm_poster_pig_Data.log)

**Comment by brentthorne** [comment]
Hello @vratchaudhary ,

Could you provide a reproducible example of the problem? Which parts of the template did you change before the knit failed? If I am able to reproduce your error then I will have the info needed to look into what may have happened.

Cheers!
