### ISSUE TITLE
Remove Canada.geojson files.. too big for only being templates

### ISSUE THREAD

**Issue by lwjohnst86** [brentthorne/posterdown#65]
On R build check, a note shows that the package size is 24 Mb, which is very large. The two json data files take up 11 Mb each. Since they aren't needed for the package (only to show poster images), I'd suggest removing them and using some other way to show the figure in the template files. If you want to submit this to CRAN, you'll have to do this anyway.

**Comment by brentthorne** [comment]
Yes its been on my list! I honestly haven't had time to go through any of the older parts and clean them up yet. I do hope to have this done and submitted to CRAN before UseR2019 though.

Eventually, I would like to remove the `posterdown_latex` and the older `posterdown_pdf` from the initial download of the package and if people want to use them they can choose to download it using a function. Similar to how the tinytex package needs you to use the `install_tinytex()` function after you have installed it on R.  Maybe I can put together a function like `install_posterdown_latex()`, but I haven't done that before so I need a little time to get that done.

Please keep sending me your feedback as it's been very helpful for me!

Cheers
