### ISSUE TITLE
Consider moving YAML theme headings into options for output

### ISSUE THREAD

**Issue by lwjohnst86** [brentthorne/posterdown#68]
The large volume of YAML configurations for setting options is quite extensive (great job) but can be bewildering. If possible maybe move the options over into the output as a single `theme` setting in the `posterdown_html` arguments. Then pass the options over as a list if desired. 

The other option would be to create a few set themes that users can use as a default.

(this is in part related to #59)

**Comment by lwjohnst86** [comment]
I haven't looked into this yet, but maybe the styling options can be moved into a css file, rather than all put into the `template.html` file.

**Comment by brentthorne** [comment]
Yes this is another task I am considering. I had limited understanding of how knitr -> pandoc -> css/html worked but now I know I can have set YAML options which are only changed if the user indicates it. The goal would be to have the default YAML header look something like:

```r
---
title: A Title
author: 
     - name: Author One
       affil: 1
affiliation:
     - num: 1
       address: Institute One
output: 
  posterdown::posterdown_html
---
```

Then all other options are added set as default and can be changed as needed (aka if they put it in the YAML then it will changed it from the default), such as poster height and width values. I am currently working on an RStudio addin which will allow the user to pick/ fill in/ change YAML information for all options and the addin will handle formatting of the YAML. I think it make for a smoother experience, both for advanced (can add in YAML options as they choose) and new users (who will have the addin help them visualize some of the changes possible).

I will just need a little bit of time to get to this, although I am setting a personal deadline for before the UseR2019 conference, if possible of course.

Cheers
