### ISSUE TITLE
Converting HTML output to PDF for printing

### ISSUE THREAD

**Issue by robwschlegel** [brentthorne/posterdown#72]
Hello,
I was very excited to see someone make a poster template in R as I'm always looking for new options to keep the whole academic process "in-house".

The output of the posterdown_betterport template is lovely but I can't seem to find any way to satisfactorily convert the output to PDF. Am I missing something? Producing an HMTL file, and then printing it to PDF does not work as the background colours disappear. 

A bit of searching online showed that this is usually caused by the canvas size (or whatever you want to call it) not being the same as the file wants it to be. So by changing the custom canvas size to match my desired dimension (841 x 1189 mm) the header background returns but not the footer. Also, the header is always grey with black text.

I am on Ubuntu 16.04, R 3.5.3, and RStudio 1.2.1335

Any advice you could offer w.r.t. PDF conversion from the HTML output would be appreciated.
All the best,
-Robert

**Comment by robwschlegel** [comment]
So I took a step back and thought about it for a while.

It turns out this is a Firefox web browser issue. I went ahead and downloaded the chromium web browser (open source chrome) and that gives one the option to turn on the background colouring etc.

Problem solved.

Thanks again for creating these templates!

-Robert

**Comment by brentthorne** [comment]
Hey thanks for trying out posterdown,

I'm glad you were able to find the solution, feel free to share your poster whenever it is done!

Cheers
