### ISSUE TITLE
Images in posterdown_betterland main_findings:

### ISSUE THREAD

**Issue by avalcarcel9** [brentthorne/posterdown#74]
Is there a way to put images in the posterdown_betterland main_findings: section? It would be nice if instead of a YAML header this section was just a normal part of the document.

**Comment by brentthorne** [comment]
Hey @avalcarcel9, thanks for using posterdown!

I have been tinkering around with adding images like you mentioned. I don't see a way to accomplish it though without using the YAML, or potentially a separate Rmd file which contains only the "Middle" material.

The goal of posterdown in general is to stay as true to clean markdown/ Rmarkdown as possible so the work written can be done distraction free and can be easily transferred to a thesis document or manuscript etc.

If there are options to pull a header section from the document and place it elsewhere then it could be possible but it is something I am looking into more.

Would your image take the entire middle space of the poster or is it just a graphic you wish to add to it?

Cheers

**Comment by avalcarcel9** [comment]
I love the package and poster templates so far so great job! I would ideally like a graphic or a few graphics to take up the whole middle section. Possibly I'd include a small amount of text with the take home points.

**Comment by brentthorne** [comment]
So I'm still working on the _'make the entire background an image'_ part of this issue but for now here is a way that you can add a plot into the main section of the poster.

1. Make a code chunk in your rmd that writes an image file of your plot, use `include=FALSE` to ensure this is not rendered in the columns of the poster as well.

````markdown
```{r myplot, include=FALSE}
svg("myplot.svg")
plot(iris$Sepal.Length, iris$Sepal.Width)
dev.off()
```
````

2. In the yaml options add the filenames of your new plot to the `main_findings:` option using markdown syntax. You will also need to add the class `{.main_pic}` to get it center aligned.

```markdown
---
main_findings:
  - "Make **better posters** with RMarkdown + **posterdown**."
  - '![](myplot.svg){.main_pic}'
---
```

Doing this will produce the dynamic plot in the center of your poster that can be placed bellow the first line of text or above or as a stand alone. Let me know if this works for you! Thanks again for the feedback.

![A Better Reproducible Poster Title-1](https://user-images.githubusercontent.com/15312739/60890128-add01e80-a228-11e9-9538-3cb9fd9ef213.png)

**Comment by avalcarcel9** [comment]
This is amazing! Thanks so much for incorporating!
