### ISSUE TITLE
`patchwork` not available for R 3.6.0

### ISSUE THREAD

**Issue by wendtke** [brentthorne/posterdown#77]
I cannot render the `posterdown` HTML template due to a dependency on `patchwork`, which is not available for R 3.6.0. Work-around? When might `posterdown` be compatible with R 3.6.0?

**Comment by brentthorne** [comment]
Hello @wendtke thanks for trying out {posterdown}!

The {patchwork} dependency isn't actually required. I have a lot of items to clean up from here, however if you remove the r-chunk which makes the figure using patchwork then it should render no problem. I will soon be adding a minimal option for {posterdown}

May I ask which template you are using? And if you are on the most recent version of posterdown?

Cheers!

**Comment by wendtke** [comment]
Thanks for the quick reply, @brentthorne !

Oh my bad, I tried to knit before removing your template chunks. I was experimenting with the HTML {posterdown} template to see if it might work for my upcoming presentation. Yes, I installed the most recent version of {posterdown} with `devtools::install_github("brentthorne/posterdown")` earlier today. 

Unfortunately, it doesn't look like I will be able to use {posterdown} for this presentation because my adviser wants me to use a (PowerPoint 👎) template from our university. 

Thanks for creating {posterdown}, though! I look forward to using it in the future.

**Comment by brentthorne** [comment]
Ah yes the old supervisor wants it that way problem, funny enough I will be giving a lightning talk at UseR2019 this year on how to deal with that! 

For now though I would suggest (if time permits) trying your hand at making the poster in {posterdown} anyways and see if you like it or not. Compare it to your Powerpoint one, consider the pros and cons of what you got out of each and then see if the supervisor has an opinion on which final product they like better. 

I also find that showing the workflow directly rather then trying to explain how RMarkdown works is a much better approach when trying to get others (specifically supervisor's) excited about reproducible, free, document generation. 

Regardless, happy postering :tada:  !

**Comment by wendtke** [comment]
That's awesome; I think I could learn a few things from your talk. I can't make it to France this year, but, hopefully, St. Louis 2020 will work! (Only my hair will like the humidity.) 

For some unfathomable reason, researchers in my department are satisfied with SPSS, Excel, PowerPoint, and the like. Maybe if they see enough pretty posters (!) or witness the ease of R tools like my fledging R package {psyphr}, they will change their minds. One can dream.
