### ISSUE TITLE
Unable to knit default posterdown::posterdown_latex template using TeXLive

### ISSUE THREAD

**Issue by N0rbert** [brentthorne/posterdown#78]
First of all I want to say "thank you" for this great project!

Then I need to describe the issue which I have on my Ubuntu 16.04.6 LTS system.
Here I have installed RStudio preview 1.2.1303 and TeXLive 2015 (from [repository](https://packages.ubuntu.com/xenial-updates/texlive-full)).

So I have installed the `posterdown` package and tried to build `Posterdown LaTeX` template file and hit Knit button. And got the following output:

```
/usr/bin/pandoc +RTS -K512m -RTS posterdown-latex.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output posterdown-latex.tex --template /home/username/R/x86_64-pc-linux-gnu-library/3.4/posterdown/rmarkdown/templates/posterdown_latex/resources/template.tex --highlight-style tango --pdf-engine pdflatex --biblatex 
output file: posterdown-latex.knit.md

! Missing number, treated as zero.
<to be read again> 
                   \edef 
l.62 \definecolor{titleboxbgcol}{HTML}{8080}

Error: Failed to compile posterdown-latex.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See posterdown-latex.log for more info.
Execution halted
```

Setting `options(tinytex.verbose = TRUE)` does not help.

Some info is below:
```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS
....
> packageVersion('tinytex')
[1] ‘0.13’
> packageVersion('posterdown')
[1] ‘0.1.2.9000’
```

I do not know what to do with this error. 
The HTML versions are knitted normally.

**Comment by brentthorne** [comment]
Hi @N0rbert thanks for trying posterdown!

I would suggest checking your YAML header as it appears you have provided only a 4 digit hex value for the option `titlebox_bgcol: "008080"`. First see if that value is correct and let me know if there is still an issue with it.

Also I am openly taking comments on why people are choosing specific output options so feel free to let me know why you chose LaTeX vs html!

Cheers!

**Comment by N0rbert** [comment]
This `titlebox_bgcol: "008080"` line was from default template - see https://github.com/brentthorne/posterdown/blob/master/inst/rmarkdown/templates/posterdown_latex/skeleton/skeleton.Rmd#L16 .

I found why it does not work - see [overleaf docs](https://www.overleaf.com/learn/latex/Using_colours_in_LaTeX):

> **\definecolor{Mycolor2}{HTML}{00F9DE}**
>    The colour Mycolor2 is created using the HTML model. Colours in this model must be created with 6 hexadecimal digits, the characters A,B,C,D,E and F must be upper-case. 

So we need to change two things in your color representation - replace preceding zeros with ones (seems to be a bug in `xcolor` package) and change all hex-letters to uppercase. 
The patch is attached - [latex_color.patch.gz](https://github.com/brentthorne/posterdown/files/3193983/latex_color.patch.gz) .

The original problem is solved by the above patch, but now I have other problems:

* I do not see references section in resulting document
* Tables are not rendered correctly
* figures, tables and references are not linked correctly (seems that some bookdown-related stuff was changed somewhat)

see [latex.pdf](https://github.com/brentthorne/posterdown/files/3194007/latex.pdf)


---

About formats - I have not yet decided which format I'll chose as final version, but LaTeX was more convenient for me. 
To have work done, I'll possibly switch to HTML.
