### ISSUE TITLE
R code chunk option results='markup' output lines prefixed with FALSE

### ISSUE THREAD

**Issue by remlapmot** [brentthorne/posterdown#79]
Hi, Thanks for this brilliant package. 

When rendering a poster when I have an R code chunk with option `results='markup'` (or if I remove the `results = 'asis'` option from the setup chunk), for example,

````
```{r, echo=TRUE, results='markup'}
1 + 1
```
````

I am getting what appears to be an erroneous FALSE prefixed on every line of the output (perhaps where a prompt symbol should be), i.e. the output chunk is appearing as follows in the knitted md file.

````
```
FALSE [1] 2
```
````

I am using the posterdown_html, posterdown_betterland, posterdown_betterport templates rendering to html.

Thanks indeed for any help,
  Tom

**Comment by brentthorne** [comment]
Hello @remlapmot !

Thank you for bringing this up, for some reason I added the knitr option `comment = FALSE` in my listing of predetermined knitr options. If you remove that line it will use the default `##` before your output lines like so:

**rmarkdown**
````md
```{r, echo=TRUE, results='markup'}
1 + 1
```
````
**result**
````md
## [1] 2
````

If you would like to remove the `##` then you can set `comment = NA` or `comment = ''`, finally if you would like a custom string like 'foo' you can use `comment = 'foo'`. 

**rmarkdown**
````md
```{r, echo=TRUE, results='markup', comment = NA}
1 + 1
```
````
**result**
````md
[1] 2
````

**Comment by remlapmot** [comment]
That's brilliant - I missed the comment chunk option.

Thanks indeed.
