### ISSUE TITLE
Following error repeatedly creeps in at l45

### ISSUE THREAD

**Issue by anupamsingh81** [brentthorne/posterdown#8]
poster repeatedly fails to compile on my ubuntu.
I installed tinytex as well but doesnt seem to work.

! Missing number, treated as zero.
<to be read again> 
                   f
l.46 \definecolor{posterbgcol}{HTML}{ffffff}

poster.log is here.
.https://pastebin.com/8XzM1kUM

**Comment by brentthorne** [comment]
Hello @anupamsingh81 ,

Could you let me know which version of Ubuntu you are running as well as your R and RStudio versions? I have just finished testing this package on Ubuntu 18.04 and have it working. 

Could you also let me know if you have changed anything in the template `.Rmd` file maybe on pastebin so I can see if there is anything there that may be the issue!

Thanks!

**Comment by brentthorne** [comment]
Many thanks ! biber seems to be causing many issues so I am looking into switching it to natbib but it will be a few days. I will be keeping the `master` version untouched for a little while now so if you want to keep up with any day-today changes you can install the `dev` branch using:

```r
devtools::install_github("brentthorne/posterdown", ref = "dev" )
```
