### ISSUE TITLE
Example environment is not numbered and not detected by posterdown

### ISSUE THREAD

**Issue by N0rbert** [brentthorne/posterdown#80]
First of all I'd like to thank you for this great project. It saved my time.

I'm using the following syntax in my `bookdown` documents

    ```{example, code-main}
    Simple main function example
    ```
    ```
    int main() {
      return 0;
    }
    ```
    As we can see from example \@ref(exm:code-main) the `main` function returns 0.

to describe the example environment. It [is allowed](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html).

But this code is ignored by `posterdown`:

![shows example ??](https://user-images.githubusercontent.com/309456/58753965-5ffd2380-84d0-11e9-8062-0078c667dfa3.png)

I can't understand why. 
It works normally in original `pagedown::poster_relaxed` (also in `pagedown::html_paged`,  `pagedown::html_letter`, `pagedown::html_resume`, `pagedown::book_crc`, `pagedown::poster_jacobs`) and in `bookdown` books...

Any ideas?

**Comment by N0rbert** [comment]
I found the problem - I have removed r code snippet below `---`:

  ```{r setup, include=FALSE}
  knitr::opts_chunk$set(
    results = 'asis',
    echo = FALSE,
    warning = FALSE,
    message = FALSE,
    fig.align = 'center'
  )
  ```

 and now it works. Thank you!

**Comment by brentthorne** [comment]
Thanks for figuring this out. I am wondering which of the knitr chunk options leads to this issue. my guess is that it is `results = "asis"` but it could be any one of them.

Again thanks for sending your feedback to help me refine this package!

**Comment by N0rbert** [comment]
I tested it further and ended with your default knitr opts and have added `echo=TRUE` to my code block:

    ```{example, code-main, echo=TRUE}
    Simple main function example
    ```
    ```
    int main() {
      return 0;
    }
    ```
Now it works as expected and do not change the behavior of your tables and r-figures :)
Thanks to [rmarkdown-reference.pdf](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf).
