### ISSUE TITLE
Monospaced fonts in title are tiny

### ISSUE THREAD

**Issue by chiphogg** [brentthorne/posterdown#82]
To reproduce: add backticks around a word in the title.  It will correctly render it in monospaced fonts, but it will be tiny.  This is apparently because the monospaced font gets turned into a `<code>` block, and the CSS for the code block specifies it as `25pt`.  Maybe it should be `1em` or some other `em` figure, so it will be relative to its environment?

(NOTE: I don't know where the `<code>` CSS styling is coming from.  It doesn't appear to be in the template.  Maybe knitr adds it?  Maybe pandoc?)

**Comment by brentthorne** [comment]
Thanks for this, I will add a the required behaviour in the next git push. The css for code blocks can be found in the template.html files, for example it can be found [here](https://github.com/brentthorne/posterdown/blob/3fbfb91e7652724577efbf6c66633c90bd856d6c/inst/rmarkdown/templates/posterdown_html/resources/template.html#L243-L250) for the `posterdown_html` output .

In the meantime if you want to change the code block in your document then you can add this to your `.Rmd` file:

```html
<style>
.poster_title code {
font-size: 1em;
}
</style>
```

That should override any code block issues in the title while not changing the default styling for code blocks within the body.

**Comment by chiphogg** [comment]
Thanks for the workaround!  In the meantime, I solved my problem by forking posterdown, and iterating on my local fork to get the CSS to do what I needed.
