### ISSUE TITLE
README unclear about how to render the poster

### ISSUE THREAD

**Issue by chiphogg** [brentthorne/posterdown#83]
It took me a while to figure out that `rmarkdown::draft()` was _creating_ a file, not rendering (a "draft" of?) an existing file.  Instead, I created my own `.Rmd` file from scratch, and was confused when:

1. Running "the command" (i.e., the `rmarkdown::draft(...)` invocation) didn't appear to produce any output.
2. Re-running "the command" would fail, because it complains the directory already exists.

Once I realized what was going on, I searched the main README, but I couldn't see how to actually render the file.  It looks like `rmarkdown::render()` is the way to go?  I've used knitr a bunch before, but the `rmarkdown` package is new to me.

I guess the resolution would be to make sure the docs clearly outline the steps to go from nothing to rendered content.

**Comment by brentthorne** [comment]
There is a lot of work I would like to do in cleaning up the readme and this is certainly on the list. I am currently working on a minimalist version of the `posterdown_html` template which the user will need to provide no yaml options for other than the obvious `output: posterdown::posterdown_html`.

However this will take some time and I am in the closing months of graduate school so I cannot guarantee any time frame for it. The `rmarkdown::render()` option is the way to go for sure as it is what I am using now (recently made the switch to vim and am starting to get a feel for working without rstudio).

Thanks for providing this feedback and please keep it coming as I am always looking to improve/ clean up this package.

Cheers

**Comment by chiphogg** [comment]
Thanks!  There is never enough time, is there?

I ended up figuring out the issues and getting the poster to render.  I wish I could share it, but it's Uber-internal, so I'd have to try to get approval, and there's no guarantee I would.

Anyway, great to see a fellow Brock grad doing really cool, high-impact work!  Thanks for this :slightly_smiling_face:

**Comment by brentthorne** [comment]
Anyone who may have rendering questions in the future please see the [wiki](https://github.com/brentthorne/posterdown/wiki/Installation-&-Usage-Guide#rendering-posters)
