### ISSUE TITLE
v1.0.0 adding email breaks poster betterland

### ISSUE THREAD

**Issue by saikong** [brentthorne/posterdown#86]
Thanks for a great package. Saw you posted my betterposter at your showcase, cool (@giladfeldman).

Took me a while to figure out why the new version betterland breaks, turns out it's the email: field for the author. Tried it on a clean poster, yep, adding email to the author breaks template.
Also seems like ORCID won't show.

I think that whole part in v1.0.0 needs a bit of testing.

Please fix, can't have a poster with no email.

**Comment by brentthorne** [comment]
Hi @saikong !

1. Thanks for reminding me about the orcid thing, I completely forgot about it but it is now functioning!

2. I've tried to reproduce your issue and am not able to get email to crash the knit process. Could you provide a code chunk with the YAML options you have fill out and how you are rending the poster (either hitting the knit button, using `pagedown::chrome_print()`, or if you are using `xaringan::inf_mr()`)

Also just make sure that the author who's email you wish to use is classified as `main: true`, that's the only other part I can think of that may be causing the problem.

```markdown
---
author:
 - name: Jon Doe
   affil: 1
   email: jon@doe.com
   orcid: 0000-0000-0000-0000
   main: true
---
```

As for the poster breaking, I noticed that the template rmd was broken, at least for me, on initial knit due to overflowing content. I would suggest looking to see if the length of your poster content (ie adding an extra line for email) is making the rest of the content spill out of the last outer column. To test this just remove some other content briefly and add the email option again and see if the poster still breaks on rendering.

Let me know how things go!

-Brent

**Comment by saikong** [comment]
It's not related to length, it even breaks on an empty poster.
@brentthorne : nothing crashes, it compiles fine, but the poster breaks by adding a line on the far right and the dimensions get all wrong.

Here:
![FireShot Capture 022 - A Better Reproducible Poster Title - ](https://user-images.githubusercontent.com/22305310/60536326-471da300-9d06-11e9-97fb-2c15ae79398a.png)

Code:
`---
title: A Better Reproducible Poster Title
author:
  - name: Brent Thorne
    affil: 1
    twitter: brentthorne18
    main: true
    email: giladfel@gmail.com
affiliation:
  - num: 1
    address: Department of Earth Sceicnes, Brock University
main_findings:
  - "Make **better posters** with RMarkdown + **posterdown**."
  - "![](https://raw.githubusercontent.com/brentthorne/posterdown/master/images/betterhexlogo.png){.main_pic}"
logoleft_name: https&#58;//raw.githubusercontent.com/brentthorne/posterdown/master/images/qr-code-black.png
logoright_name: https&#58;//raw.githubusercontent.com/brentthorne/posterdown/master/images/betterhexlogo.png
output: 
  posterdown::posterdown_betterland:
    self_contained: false
    pandoc_args: --mathjax
    highlight: haddock
    number_sections: false
link-citations: true
bibliography: packages.bib
---

```{r, include=FALSE}
knitr::opts_chunk$set(results = 'asis',
                      echo = FALSE,
                      warning = FALSE,
                      tidy = FALSE,
                      message = FALSE,
                      fig.align = 'center',
                      out.width = "100%")
options(knitr.table.format = "html") 
```

# Introduction

This is the `posterdown_betterland` template for the {posterdown} package! I was inspired by the twitter thread of [Mike Morrison](https://mobile.twitter.com/mikemorrison/status/1110191245035479041) and wanted to apply the `#betterposter` concept to the reproducible (yet simple to use) functionality of the {posterdown} package [@R-posterdown]. If you're not an R user don't sweat as you do **NOT** need to use it at all! Feel free to use only the Markdown functionality of this package :)

```{r, include=FALSE}
knitr::write_bib(c('posterdown', 'rmarkdown','pagedown'), 'packages.bib')
```

## Objectives

1. Pick a template layout.
2. Write/ create your poster content distraction free.
3. Let posterdown do its thing!

# Methods

I will show here how to include poster elements that may be useful, such as an equation using mathjax:

$$
E = mc^2
$$

To reference a citation you can add your `.bib` file to the working directory and name it in the YAML metadata or generate an automated one as done here, then you only need to reference the label value in the `.bib` file. For example this package is built on top of the wonderful {pagedown} package and I will cite it at the end of this sentance using this in the rmd `[@R-pagedown]` [@R-pagedown].


# Results

Here you may have some figures to show off, bellow I have made a scatterplot with the infamous Iris dataset and I can even reference to the figure automatically like this, `Figure \@ref(fig:irisfigure)`, Figure \@ref(fig:irisfigure).

```{r, irisfigure, fig.cap='Here is a caption for the figure. This can be added by using the "fig.cap" option in the r code chunk options, see this [link](https://yihui.name/knitr/options/#plots) from the legend himself, [Yihui Xie](https://twitter.com/xieyihui).'}

plot(x = iris$Sepal.Length, y = iris$Sepal.Width,
     col = iris$Species, pch = 19, xlab = "Sepal Length",
     ylab = "Sepal Width")
```

Maybe you want to show off some of that fancy code you spent so much time on to make that figure, well you can do that too! Just use the `echo=TRUE` option in the r code chunk options, Figure \@ref(fig:myprettycode)!

```{r myprettycode, echo=TRUE,collapse=TRUE, fig.cap='Boxplots, so hot right now!', fig.height=3.5, out.width="100%"}
#trim whitespace
par(mar=c(2,2,0,0))
#plot boxplots
boxplot(iris$Sepal.Width~iris$Species,
        col = "#008080", 
        border = "#0b4545",
        ylab = "Sepal Width (cm)",
        xlab = "Species")
```

How about a neat table of data? See, Table \@ref(tab:iristable):

```{r, iristable}
knitr::kable(
  iris[1:3,1:5], format = "html",
  caption = "A table made with the **knitr::kable** function.",
  align = "c", col.names = c("Sepal <br> Length",
                             "Sepal <br> Width",
                             "Petal <br> Length",
                             "Petal <br> Width",
                             "Species"),
  escape = FALSE)
```

# References
`

**Comment by brentthorne** [comment]
Okay I think I fixed that with a previous commit, there were some issues with <dev> class names that I found. Can you try out the latest version of posterdown from github and see if you get the same problem?

**Comment by saikong** [comment]
Installed latest, tried it again, sorry, unless I'm missing something obvious - still breaks, try it yourself on a clean install.

**Comment by brentthorne** [comment]
Hmm that's odd, unfortunately all parts are working on my end even with a clean install on multiple machines. To confirm latest updates you can specify the exact commit to download using:

`devtools::install_github(repo = "brentthorne/posterdown", ref = "ad2ddc9bfeb43b105187931ee09edc325391afdc")`

and then see if creating a new rmarkodown document with the betterland template works without changes.

Also , are you viewing your output in chrome, firefox, safari, or straight to a pdf? As well I may ask for what operating system you are running and such, maybe if you could provide your session info as well I can look into that.

Hopefully we can figure this out soon so you can get your poster finished!

**Comment by saikong** [comment]
Okay, I see what happened here. I had the latest version, but the poster code needed changing.

I created a new poster and saw some changes you made to width from the previous versoin, that made the difference. Was able to translate that to changes in my poster.

Many thanks for being so responsive. Really great work, I'm in your debt.

Can close the issue now.

**Comment by brentthorne** [comment]
No problem glad that you are getting use out of this package and feel free to submit an issue any time there is something that you are stuck on!
