### ISSUE TITLE
echo=TRUE in code chunk causes layout errors for both better poster templates

### ISSUE THREAD

**Issue by brentthorne** [brentthorne/posterdown#87]
Error happens when code chunk has `echo=TRUE`

Need to look which changes made recently may have caused this.

As of right now it is not possible to "view" the code of an R chunk as it causes this error.

**Comment by remlapmot** [comment]
I am also seeing this issue. 

I am using betterport.

It looks like in the generated html poster file that `<pre class="sourceCode r">...</pre>` tags, which I think come from 
````
```r
...r code...
```
````
chunks from the knitted md file, are being appended with an extra `</div>`. 

I don't know if this means that there is a missing `<div >` which should come before the `<pre >` tags or if the final `</div>` should not be there.

When I manually delete the extra `</div>` my poster looks fine in my browser again.

But I don't know what is causing this `</div>` mismatch.

Apologies if you knew all of this.

**Comment by brentthorne** [comment]
Thanks for pointing this out @remlapmot I did not see this before!

That `</div>` tag should definitely not be there, now to figure out why it is generated and  how to get rid of it. Maybe @yihui or @RLesur have ideas?

Thanks again!

**Comment by yihui** [comment]
Try this: https://github.com/rstudio/bookdown/issues/733#issuecomment-506924672

**Comment by remlapmot** [comment]
That's great @yihui. As suggested in that issue, I have updated my bookdown to the github version with 
```r
remotes::install_github("rstudio/bookdown")
```
and that has solved this problem for me (as I guess it has an updated version of the `clean_pandoc2_highlight_tags()` function).

**Comment by yihui** [comment]
@remlapmot Great! I'll try to release a new version of **bookdown** to CRAN soon since this has definitely affected multiple users. Thanks for testing!

**Comment by brentthorne** [comment]
This is great thank you @remlapmot and @yihui ! I'll keep this open until that CRAN release happens for others who might experiences this!

Cheers!
