### ISSUE TITLE
Change number of columns

### ISSUE THREAD

**Issue by LGurtner** [brentthorne/posterdown#95]
Hello and thanks for the great package, it is saving me a lot of time! However, at the moment I am struggling with the number of columns. I decided that I would prefer 2 columns in my portrait-poster instead of 3. I tried adapting the HTML-Template just as suggested in the Column break trick, but I don't know much about HTML or CSS itself. In line 142 in the HTML deplate it says: 

`-webkit-column-count: $if(column_numbers)$$column_numbers$$else$3$endif$; /* Chrome, Safari, Opera */
-moz-column-count: $if(column_numbers)$$column_numbers$$else$3$endif$; /* Firefox */
column-count: $if(column_numbers)$$column_numbers$$else$3$endif$;`

and I tried to change the 3 in the *else* command for a 2 but it didn't work, there are still 3 columns. I can't find out where to set the value for `column_numbers`, could you help me? Thank you very much!
Lilla

**Comment by brentthorne** [comment]
Hello!

Have you tried setting the value in the YAML options? Your header would look like this:

```md
---
title: Some title
column_numbers: 2
output: posterdown:: posterdown_betterport
---

# Introduction
```

**Comment by LGurtner** [comment]
Hey, 

I didn't try but that did the trick. Sometimes it's the simple things...
Thank you!!
