### ISSUE TITLE
More whitespace towards right then left

### ISSUE THREAD

**Issue by dktanwar** [brentthorne/posterdown#97]
Hello,

Thanks for the package, it's great!

I am having some problems here. I have more space towards right then left.

[Deepak_Tanwar.pdf](https://github.com/brentthorne/posterdown/files/3530550/Deepak_Tanwar.pdf)

How can I fix this issue?

**Comment by brentthorne** [comment]
Thanks for trying it out! It looks to me that your Figure #4 is wider than the width of the the column, this would cause alignment issues for anything after it (ie only the right column). 

If you are using r code chunks to show your images I would suggest using the chun option `out.width=` and set it to `"95%"`. So the chunk would be something like this:

````markdown
```{r, myfigure, out.width="95%"}
knitr::includegraphics("path/to/your/image.png")
```
````  

This will ensure that the image will only take up a total of 95% of the width of the column it is placed into.

Let me know if that works!

**Comment by dktanwar** [comment]
Sorry, it didn't work.

Not sure if I was able to explain it properly. I kind of marked the space I was talking about (not so ugly).

[Deepak_Tanwat_v2.pdf](https://github.com/brentthorne/posterdown/files/3531172/Deepak_Tanwat_v2.pdf)

**Comment by brentthorne** [comment]
Ahh I see it better now, it looks like you have the border set on the title section of the poster. I am still working on a way to fix this but for now the easiest fix would be to remove the border. Ill let you know once I get the fix for this working.

**Comment by dktanwar** [comment]
True that!

But, I don't see that issue on the example poster: https://brentthorne.github.io/posterdown_html_showcase/

**Comment by brentthorne** [comment]
You are correct, the example poster is quite old and needs to be updated, thanks for notifying me of this!

**Comment by dktanwar** [comment]
OK. So that issue seems to be solved, but a new issue:

Now, towards to right of the poster, I see a dashed line:

![Screen Shot 2019-08-23 at 11 44 13](https://user-images.githubusercontent.com/8986859/63583519-741a6380-c59b-11e9-8054-63db70521e69.png)

**Comment by brentthorne** [comment]
Hi @dktanwar 

The extra line that you are getting is due to an overflow of content. Either some of your figure/ text are just too long for the last column or when you view the document in the browser you can have this issue if your zoom level is not set 100%. This can happen even when the content doesn't appear to be overflowing (or too long) in the last column because if it reaches the bottom it may add a space or break right after thus leaving a new column with nothing in it and that would generate a new column line like you have. 

 I probably won't implement the change in default line colour as per your pull request which would change the colour of all the lines and just "hides" the overflow problem you have rather then fix it.

**Comment by dktanwar** [comment]
Hi @brentthorne 

I actually changed that 1 thing in the `posterdown_html/resources/template.html` file and seems to work.

[shortRNA_DKT_PLG_EI_2019.pdf](https://github.com/brentthorne/posterdown/files/3535651/shortRNA_DKT_PLG_EI_2019.pdf)

**Comment by dktanwar** [comment]
I made the change in the installed package folder of the package

**Comment by brentthorne** [comment]
@dktanwar I am going to close this issue as the initial problem has been fixed. Please feel free to submit a new issue for the secondary problem you mention in this thread. As for the [pull request](https://github.com/brentthorne/posterdown/pull/98) you made I would kindly ask that you add a brief description of your reasoning for the changes to the files you made. 

Cheers!
